php:
  build: php-fpm
  volumes:
    - /srv:/srv
  links:
    - db:db
  environment:
    TERM: xterm  # fixes for some commands in bash inside container.

web:
  build: nginx
  ports:
    - "8888:8080"
  links:
    - php
  volumes:
    - /srv:/srv

db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: "u_project"
    MYSQL_PASSWORD: "p_project"
    MYSQL_DATABASE: "project"
